#pragma once

// DISPLAY CONSTANTS
// Store constants having to do with the display on the screen

const int MAX_NUM_FONTS = 10;

// Draw Enums
enum font_types
{
	FONT_DEFAULT,
	FONT_LARGE,
	FONT_LARGE_BOLD,
	FONT_SMALL
};

const int SCREEN_WIDTH = 1920;
const int SCREEN_HEIGHT = 1080;

const int TILE_SIZE = 32;
const int SPRITE_SIZE = 32;

const int DISPLAY_MAX_ZOOM = 64;
const int DISPLAY_MIN_ZOOM = 16;

const int MAX_NUM_PRIMITIVES = 500;
const int MAX_NUM_TEXT_PRINT = 500;
const int MAX_SPRITE_INSTRUCTIONS = 4000;
const int MAX_SPRITES_PER_MULTISPRITE = 400;



enum spritesheets
{
	SPRITESHEET_NONE,
	SPRITESHEET_BACKGROUND,
	SPRITESHEET_BASE,
	SPRITESHEET_BASE_OVERLAY,
	SPRITESHEET_MID_1,
	SPRITESHEET_MID_1_OVERLAY,
	SPRITESHEET_MID_2,
	SPRITESHEET_ENTITY,
	SPRITESHEET_ROOF,
	SPRITESHEET_ICON
};


// MESSAGE BUS CONSTANTS
// Store constants having to do with the message bus
const int MAX_INPUT_MESSAGES = 10;
const int MAX_CHATTER_MESSAGES = 10;
const int MAX_SG_TILE_UPDATE_MESSAGES = 1000;
const int MAX_LENGTH_CUSTOM_MESSAGE = 100;
const int MAX_NUM_CUSTOM_MESSAGES = 1000;

// Custom Message Type Enums
enum Custom_Message_Type
{
	MESSAGE_TYPE_NULL,
	MESSAGE_TYPE_STAT_UPDATE_REQUEST,
	MESSAGE_TYPE_SG_TILE_UPDATE_NOTIFICATION,
	MESSAGE_TYPE_SG_ENTITY_CREATE,
	MESSAGE_TYPE_SG_TILE_UPDATE_REQUEST,
	MESSAGE_TYPE_CURSOR_STATUS_UPDATE,
	MESSAGE_TYPE_SET_ENTITY_RALLY_POINT
};

enum Stat_Update_Request_Type
{
	STAT_ADJUST,
	STAT_UPDATE
};

enum Custom_Message_Focus
{
	FOCUS_NULL,
	FOCUS_SPECIFC_OBJECT,
	FOCUS_RANGE,
	FOCUS_ALL
};




// UI CONSTANTS
const int UI_MAX_INPUT_MESSAGES = 100;
const int UI_MAX_CONSOLE_MESSAGES = 200;
const int UI_CONSOLE_MESSAGE_LIFETIME = 100;
const int UI_MAX_WINDOW_HEADERS = 5;
const int UI_MAX_CONSOLE_PANELS = 10;
const int UI_MAX_NUM_PANEL_COMPONENTS = 10;

enum mouse_buttons
{
	MOUSE_LEFT,
	MOUSE_MIDDLE,
	MOUSE_RIGHT
};

enum input_actions
{
	INPUT_NULL,
	INPUT_LEFT_MOUSE_CLICK,
	INPUT_LEFT_MOUSE_DRAG,
	INPUT_LEFT_MOUSE_UNCLICK,
	INPUT_RIGHT_MOUSE_CLICK,
	INPUT_RIGHT_MOUSE_DRAG,
	INPUT_RIGHT_MOUSE_UNCLICK
};

enum window_names
{
	WINDOW_NULL,
	WINDOW_PLAYER_DIAGNOSTIC,
	WINDOW_CREATE_STRUCTURE,
	WINDOW_SCREEN_BUTTONS
};

enum panel_names
{
	PANEL_NULL,
	PANEL_MESSAGE_STREAM,
	PANEL_STRUCTURE_CREATE_WALL,
	PANEL_STRUCTURE_CREATE_FLOOR,
	PANEL_STRUCTURE_CREATE_MISC
};

enum button_actions
{
	BUTTON_ACTION_DO_NOTHING,
	BUTTON_ACTION_DRAG_WINDOW,
	BUTTON_ACTION_SWITCH_PANEL,
	BUTTON_ACTION_CLOSE_WINDOW
};

enum Action_Message_Category
{
	UI_ACTION_CATEGORY_NULL,
	UI_ACTION_CATEGORY_SUPPORTING,
	UI_ACTION_CATEGORY_MAIN
};

enum Main_Action_Message_Type
{
	UI_ACTION_MAIN_TYPE_NULL,
	UI_ACTION_MAIN_TYPE_CLICK_IN_WORLD
};

enum Supporting_Action_Message_Types
{
	UI_ACTION_SUPPORTING_TYPE_NULL,
	UI_ACTION_SUPPORTING_TYPE_SET_STRUCTURE_BUILD,
	UI_ACTION_SUPPORTING_TYPE_DELETE_STRUCTURE,
	UI_ACTION_SUPPORTING_TYPE_SET_RALLY_POINT
};

// GAME LIBRARY CONSTANTS

const int MAX_NUM_TILE_TEMPLATES = 50;
const int MAX_NUM_ENTITY_TEMPLATES = 50;

// SCENE GRAPH CONSTANTS

const int WORLD_MAX_NUM_STRUCTURES = 1000;
const int WORLD_MAX_NUM_ENTITIES = 100;

// Each background object takes about 1 FPS off the total so adjust judiciously
const int WORLD_MAX_NUM_BACKGROUND_OBJECTS = 500;

enum Assigned_Flag
{
	OBJECT_UNASSIGNED,
	OBJECT_ASSIGNED
};

enum Entity_Types
{
	OBJECT_TYPE_NULL,
	OBJECT_TYPE_STRUCTURE,
	OBJECT_TYPE_ENTITY,
	OBJECT_TYPE_ITEM,
	OBJECT_TYPE_CONTAINER,
	OBJECT_TYPE_PROJECTILE,
	OBJECT_TYPE_ANY
};

enum Tile_Layers
{
	TILE_LAYER_BACKGROUND,
	TILE_LAYER_BASE,
	TILE_LAYER_MID,
	TILE_LAYER_ROOF
};

// AI Stats Enums

enum Structure_Types
{
	STRUCTURE_TYPE_NULL
};

enum Structure_Ids
{
	STRUCTURE_ID_NULL
};

enum Entity_ID
{
	ENTITY_ID_NULL
};

const int MAX_STRUCTURE_STATS = 20;

enum Structure_Stat
{
	STAT_STRUCTURE_NULL,
	STAT_STRUCTURE_BUILT_LEVEL,
	STAT_STRUCTURE_STRUCTURE_HEALTH,
	STAT_STRUCTURE_STRUCTURE_MAX_HEALTH,
	STAT_STRUCTURE_OXYGEN_LEVEL,
	STAT_STRUCTURE_POWERED,
	STAT_STRUCTURE_IMPASSABLE,
	STAT_ENTITY_HEALTH,
	STAT_ENTITY_MAX_HEALTH,
	STAT_ENTITY_HUNGER,
	STAT_ENTITY_TIREDNESS,
	STAT_ENTITY_OXYGEN,
	STAT_ENTITY_FEAR,
	STAT_ENTITY_SPEED,
	STAT_ENTITY_ENNUI
};

// Render Component Enums

enum Render_Component_Type
{
	RENDER_COMPONENT_NONE,
	RENDER_COMPONENT_BACKGROUND,
	RENDER_COMPONENT_SIMPLECLIP,
	RENDER_COMPONENT_MULTICLIP,
	RENDER_COMPONENT_ANIMATED_CLIP,
	RENDER_COMPONENT_ENTITY_SIMPLE,
	RENDER_COMPONENT_ENTITY_COMPLEX
};

enum Multiclip_Type
{
	MULTICLIP_NONE,
	MULTI_CLIP_WALL,
	MULTI_CLIP_FLOOR
};

enum ENTITY_ANIMATIONS
{
	ANIM_WALK_DOWN,
	ANIM_WALK_UP,
	ANIM_WALK_LEFT,
	ANIM_WALK_RIGHT
};

const int MAX_NUM_ANIMATIONS = 4;
const int MAX_NUM_COMPONENTS = 5;

// AI_JOB ENUMS

const int MAX_LENGTH_GOAL_INSTRUCTION = 50;
const int MAX_NUM_GOAL_INSTRUCTION = 20;


enum Job_Types
{
	JOB_NONE,
	JOB_OXYGENATE_SURROUNDINGS
};

enum Goal_Actions
{
	ACTION_NONE,
	ACTION_CREATE,
	ACTION_DESTROY,
	ACTION_EDIT_INTERNAL,
	ACTION_EDIT_EXTERNAL,
	ACTION_ASSESS_INTERNAL,
	ACTION_ASSESS_EXTERNAL,
	ACTION_TRANSFER
};

enum Assess_External_Types
{
	A_AE_NULL,
	A_AE_OXYGENATE
};

// AI Inventory Constants

const int MAX_NUM_INVENTORY_SLOTS = 20;
const int MAX_NUM_EQUIPMENT_SLOTS = 10;
const int MAX_NUM_ITEM_BLUEPRINTS = 10;
const int MAX_ITEMS_PER_BLUEPRINT = 10;

enum Equipment_slots
{
	EQUIPMENT_SLOT_NULL,
	EQUIPMENT_SLOT_SPACESUIT
};

// AI Movement 

const int SEARCH_WIDTH = 100;
const int SEARCH_HEIGHT = 100;